name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ ubuntu-latest , windows-latest ]
        java: [ 8, 11, 13 ]
        experimental: [ false ]

    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1.4.2
        with:
          java-version: ${{ matrix.java }}
      - name: Build with mvn
        run: |
          cd ./base
          mvn install
          cd ../
          cd ./user
          mvn install